-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 00:05:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `MID` INT NOT NULL,
  PRIMARY KEY (`MID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branch` (
  `BID` INT NOT NULL,
  `BAddress` VARCHAR(100) NOT NULL,
  `MGR_EID` INT NOT NULL,
  `Startdate` DATETIME NULL,
  `MID` INT NOT NULL,
  PRIMARY KEY (`BID`),
  INDEX `MID_idx` (`MID` ASC) VISIBLE,
  INDEX `MGR_EID_idx` (`MGR_EID` ASC) VISIBLE,
  CONSTRAINT `MID`
    FOREIGN KEY (`MID`)
    REFERENCES `mydb`.`Menu` (`MID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MGR_EID`
    FOREIGN KEY (`MGR_EID`)
    REFERENCES `mydb`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EID` INT NOT NULL,
  `EName` VARCHAR(50) NOT NULL,
  `Gender` VARCHAR(10) NULL,
  `EAddress` VARCHAR(100) NULL,
  `EPhone` INT NOT NULL,
  `Salary` INT NOT NULL,
  `Shift` VARCHAR(50) NOT NULL,
  `BID` INT NOT NULL,
  PRIMARY KEY (`EID`),
  INDEX `BID_idx` (`BID` ASC) VISIBLE,
  CONSTRAINT `BID`
    FOREIGN KEY (`BID`)
    REFERENCES `mydb`.`Branch` (`BID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chef` (
  `Role` VARCHAR(50) NOT NULL,
  `ChefID` INT NOT NULL,
  PRIMARY KEY (`ChefID`),
  CONSTRAINT `ChefID`
    FOREIGN KEY (`ChefID`)
    REFERENCES `mydb`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Waiter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Waiter` (
  `Rating` VARCHAR(50) NOT NULL,
  `WaiterID` INT NOT NULL,
  PRIMARY KEY (`WaiterID`),
  CONSTRAINT `WaiterID`
    FOREIGN KEY (`WaiterID`)
    REFERENCES `mydb`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cashier` (
  `CashierID` INT NOT NULL,
  PRIMARY KEY (`CashierID`),
  CONSTRAINT `CashierID`
    FOREIGN KEY (`CashierID`)
    REFERENCES `mydb`.`Employee` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dish` (
  `DID` INT NOT NULL,
  `DName` VARCHAR(50) NOT NULL,
  `Price` INT NOT NULL,
  `Description` VARCHAR(200) NULL,
  `MID` INT NOT NULL,
  PRIMARY KEY (`DID`),
  INDEX `MID_idx` (`MID` ASC) VISIBLE,
  CONSTRAINT `MID`
    FOREIGN KEY (`MID`)
    REFERENCES `mydb`.`Menu` (`MID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `BID` INT NOT NULL,
  `Discount` FLOAT NULL,
  `Total` VARCHAR(45) NOT NULL,
  `CashỉeID` INT NOT NULL,
  PRIMARY KEY (`BID`),
  INDEX `CashierID_idx` (`CashỉeID` ASC) VISIBLE,
  CONSTRAINT `CashierID`
    FOREIGN KEY (`CashỉeID`)
    REFERENCES `mydb`.`Cashier` (`CashierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CPhone` INT NOT NULL,
  `CName` VARCHAR(50) NOT NULL,
  `CAddress` VARCHAR(100) NULL,
  `BID` INT NOT NULL,
  PRIMARY KEY (`CPhone`),
  INDEX `BID_idx` (`BID` ASC) VISIBLE,
  CONSTRAINT `BID`
    FOREIGN KEY (`BID`)
    REFERENCES `mydb`.`Bill` (`BID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `OID` INT NOT NULL,
  `Datetime` DATETIME NOT NULL,
  `WaiterID` INT NOT NULL,
  `CPhone` INT NOT NULL,
  PRIMARY KEY (`OID`),
  INDEX `CPhone_idx` (`CPhone` ASC) VISIBLE,
  INDEX `WaiterID_idx` (`WaiterID` ASC) VISIBLE,
  CONSTRAINT `CPhone`
    FOREIGN KEY (`CPhone`)
    REFERENCES `mydb`.`Customer` (`CPhone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `WaiterID`
    FOREIGN KEY (`WaiterID`)
    REFERENCES `mydb`.`Waiter` (`WaiterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `CPhone` INT NOT NULL,
  `Datetime` DATETIME NOT NULL,
  `NummOfSeats` INT NOT NULL,
  PRIMARY KEY (`Datetime`, `CPhone`),
  CONSTRAINT `CPhone`
    FOREIGN KEY (`CPhone`)
    REFERENCES `mydb`.`Customer` (`CPhone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Include`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Include` (
  `OID` INT NOT NULL,
  `DID` INT NOT NULL,
  `Quantity` VARCHAR(50) NULL,
  PRIMARY KEY (`OID`, `DID`),
  INDEX `DID_idx` (`DID` ASC) VISIBLE,
  CONSTRAINT `OID`
    FOREIGN KEY (`OID`)
    REFERENCES `mydb`.`Order` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DID`
    FOREIGN KEY (`DID`)
    REFERENCES `mydb`.`Dish` (`DID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prepare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prepare` (
  `OID` INT NOT NULL,
  `ChefID` INT NOT NULL,
  PRIMARY KEY (`OID`, `ChefID`),
  INDEX `ChefID_idx` (`ChefID` ASC) VISIBLE,
  CONSTRAINT `OID`
    FOREIGN KEY (`OID`)
    REFERENCES `mydb`.`Order` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ChefID`
    FOREIGN KEY (`ChefID`)
    REFERENCES `mydb`.`Chef` (`ChefID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
